services:
  - type: web
    name: discord-reminder-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: TRELLO_API_KEY
        sync: false
      - key: TRELLO_TOKEN
        sync: false
      - key: TRELLO_BOARD_ID
        sync: false
      - key: TRELLO_USER_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_PORT
        value: 10000
